export { VoyaBajoLogo } from './VoyaBajoLogo'
export { HeroSection_VoyaBajo } from './HeroSection_VoyaBajo'
export { PremiumLabuanBajoHero } from './PREMIUM_LABUAN_BAJO_BACKGROUND'
export { default as PremiumLandingPage } from './PREMIUM_LANDING_PAGE'
export { default as LaGattaLandingPage } from './LAGATTA_LANDING_PAGE'
